//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activitati_Curente
    {
        public int Id { get; set; }
        public string Nume_Activitate { get; set; }
        public Nullable<int> Cod_Activitate { get; set; }
        public string Detalii_Tip_Activitate { get; set; }
        public string Subiect_Activitate { get; set; }
        public string Referinta_Subiect { get; set; }
        public Nullable<int> Cod_Subiect { get; set; }
        public string Detalii_Subiect { get; set; }
        public Nullable<decimal> Nivel_Financiar_Subiect { get; set; }
        public Nullable<byte> Timp_Afectat_Subiect { get; set; }
        public System.DateTime Data_Scadenta { get; set; }
        public Nullable<byte> Ora_Activitate { get; set; }
        public Nullable<byte> Durata_Activitate { get; set; }
        public Nullable<decimal> Grad_Realizare { get; set; }
        public Nullable<byte> Prioritate_Activitate { get; set; }
        public string Stare_Activitate { get; set; }
        public Nullable<int> Cod_Stare_Activitate { get; set; }
        public string Comentariu_Activitate { get; set; }
        public Nullable<int> Index_Reprogramare_Activitate { get; set; }
        public Nullable<int> Index_Amanare_Activitate { get; set; }
        public Nullable<bool> Activitate_Activa { get; set; }
        public Nullable<bool> Z_Bit_Field { get; set; }
        public Nullable<int> Z_Int_Field { get; set; }
        public string Z_String_Field { get; set; }
        public string Z_Text_Field { get; set; }
        public string User_Alocat { get; set; }
        public System.DateTime Data_Alocare { get; set; }
        public string Id_User { get; set; }
        public Nullable<System.DateTime> Data_Intro { get; set; }
        public Nullable<System.DateTime> Data_Modif { get; set; }
    }
}
