//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_CRUD
    {
        public int ID_Audit { get; set; }
        public string Nume_Client_Audit { get; set; }
        public string ID_User_Audit { get; set; }
        public Nullable<System.DateTime> Data_Operatiune { get; set; }
        public string Operatiune_CRUD { get; set; }
        public string Mesaj_Audit { get; set; }
    }
}
