//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clienti_Profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clienti_Profil()
        {
            this.Clienti_Contact = new HashSet<Clienti_Contact>();
        }
    
        public int ID_PRE_Client { get; set; }
        public string Tip_Client_PF_PJ { get; set; }
        public string Nume_Client { get; set; }
        public string Cod_Client { get; set; }
        public string Tara { get; set; }
        public string Domeniu { get; set; }
        public string Cod_Domeniu { get; set; }
        public Nullable<decimal> CA_Ultimul_An { get; set; }
        public Nullable<int> Nr_Angajati { get; set; }
        public string Sursa_Info_Client { get; set; }
        public string Sursa_Info_Client_Alt { get; set; }
        public string ID_USER { get; set; }
        public Nullable<System.DateTime> Data_Intro { get; set; }
        public Nullable<System.DateTime> Data_Modif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clienti_Contact> Clienti_Contact { get; set; }
    }
}
