//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clienti_Interlocutor
    {
        public int ID { get; set; }
        public Nullable<int> ID_PRE_Client { get; set; }
        public Nullable<System.DateTime> Data_Discutie { get; set; }
        public string Obs_Tipuri_Produse_Cautate { get; set; }
        public string Obs_Furnizori_Actuali_Client { get; set; }
        public string Obs_Dureri_Client { get; set; }
        public string Obs_Alte_Observatii { get; set; }
        public Nullable<int> Durata_Discutie_Minute { get; set; }
        public Nullable<int> ID_Discutie { get; set; }
        public string Tip_Discutie { get; set; }
        public string Tip_STADIU_DISCUTIE { get; set; }
        public string ID_USER { get; set; }
        public Nullable<System.DateTime> Data_Intro { get; set; }
        public Nullable<System.DateTime> Data_Modif { get; set; }
    }
}
