//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRM_Prospectare_Context : DbContext
    {
        public CRM_Prospectare_Context()
            : base("name=CRM_Prospectare_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prospecte_Contact> Prospecte_Contact { get; set; }
        public virtual DbSet<Prospecte_ContactPlus> Prospecte_ContactPlus { get; set; }
        public virtual DbSet<Prospecte_Pasi_Urmatori> Prospecte_Pasi_Urmatori { get; set; }
        public virtual DbSet<Prospecte_Profil> Prospecte_Profil { get; set; }
        public virtual DbSet<Prospecte_ProfilPlus> Prospecte_ProfilPlus { get; set; }
        public virtual DbSet<VwDashboardProspect> VwDashboardProspects { get; set; }
        public virtual DbSet<Predef_SubTipuri_Activitati> Predef_SubTipuri_Activitati { get; set; }
        public virtual DbSet<Predef_Tipuri_Activitati> Predef_Tipuri_Activitati { get; set; }
        public virtual DbSet<Activitati_Curente> Activitati_Curente { get; set; }
        public virtual DbSet<Predef_Durate_Activitati> Predef_Durate_Activitati { get; set; }
    
        public virtual int spAdaugaPasUrmator(Nullable<int> id_Prospect, string nume_Pas, Nullable<int> cod_Nume_Pas, Nullable<System.DateTime> data_Scadenta_Pas, string stare_Pas, Nullable<int> cod_Stare_Pas, Nullable<int> index_Efectuare_Pas, Nullable<int> index_Neefectuare_Pas, Nullable<int> index_Reprogramare_Pas, Nullable<bool> pas_Activ, Nullable<byte> ora_Pas, Nullable<byte> durata_Pas, Nullable<decimal> grad_Realizare_Pas, Nullable<byte> prioritate_Pas, string raspuns_Pas, string referinta_Raspuns_Pas, Nullable<int> cod_Raspuns_Pas, string detalii_Raspuns_Pas, Nullable<decimal> nivel_Financiar_Subiect, Nullable<int> timp_Afectat_Subiect_Pas, string obstacol_Pas, Nullable<int> cod_Obstacol_Pas, string comentariu_Obstacol_Pas, string comentariu_Automat_Pas, string info_Tipuri_Produse_Cautate, string info_Detalii_Produse_Cautate, string info_Furnizori, string info_Furnizor_Principal, string info_Detalii_Furnizori, string info_Tip_Motivatii, string info_Detalii_Motivatii, string info_Alte_Info, string conexe_Subiect, string referinta_Conexe_Subiect, Nullable<int> cod_Conexe_Subiect, string detalii_Conexe_Subiect, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var id_ProspectParameter = id_Prospect.HasValue ?
                new ObjectParameter("Id_Prospect", id_Prospect) :
                new ObjectParameter("Id_Prospect", typeof(int));
    
            var nume_PasParameter = nume_Pas != null ?
                new ObjectParameter("Nume_Pas", nume_Pas) :
                new ObjectParameter("Nume_Pas", typeof(string));
    
            var cod_Nume_PasParameter = cod_Nume_Pas.HasValue ?
                new ObjectParameter("Cod_Nume_Pas", cod_Nume_Pas) :
                new ObjectParameter("Cod_Nume_Pas", typeof(int));
    
            var data_Scadenta_PasParameter = data_Scadenta_Pas.HasValue ?
                new ObjectParameter("Data_Scadenta_Pas", data_Scadenta_Pas) :
                new ObjectParameter("Data_Scadenta_Pas", typeof(System.DateTime));
    
            var stare_PasParameter = stare_Pas != null ?
                new ObjectParameter("Stare_Pas", stare_Pas) :
                new ObjectParameter("Stare_Pas", typeof(string));
    
            var cod_Stare_PasParameter = cod_Stare_Pas.HasValue ?
                new ObjectParameter("Cod_Stare_Pas", cod_Stare_Pas) :
                new ObjectParameter("Cod_Stare_Pas", typeof(int));
    
            var index_Efectuare_PasParameter = index_Efectuare_Pas.HasValue ?
                new ObjectParameter("Index_Efectuare_Pas", index_Efectuare_Pas) :
                new ObjectParameter("Index_Efectuare_Pas", typeof(int));
    
            var index_Neefectuare_PasParameter = index_Neefectuare_Pas.HasValue ?
                new ObjectParameter("Index_Neefectuare_Pas", index_Neefectuare_Pas) :
                new ObjectParameter("Index_Neefectuare_Pas", typeof(int));
    
            var index_Reprogramare_PasParameter = index_Reprogramare_Pas.HasValue ?
                new ObjectParameter("Index_Reprogramare_Pas", index_Reprogramare_Pas) :
                new ObjectParameter("Index_Reprogramare_Pas", typeof(int));
    
            var pas_ActivParameter = pas_Activ.HasValue ?
                new ObjectParameter("Pas_Activ", pas_Activ) :
                new ObjectParameter("Pas_Activ", typeof(bool));
    
            var ora_PasParameter = ora_Pas.HasValue ?
                new ObjectParameter("Ora_Pas", ora_Pas) :
                new ObjectParameter("Ora_Pas", typeof(byte));
    
            var durata_PasParameter = durata_Pas.HasValue ?
                new ObjectParameter("Durata_Pas", durata_Pas) :
                new ObjectParameter("Durata_Pas", typeof(byte));
    
            var grad_Realizare_PasParameter = grad_Realizare_Pas.HasValue ?
                new ObjectParameter("Grad_Realizare_Pas", grad_Realizare_Pas) :
                new ObjectParameter("Grad_Realizare_Pas", typeof(decimal));
    
            var prioritate_PasParameter = prioritate_Pas.HasValue ?
                new ObjectParameter("Prioritate_Pas", prioritate_Pas) :
                new ObjectParameter("Prioritate_Pas", typeof(byte));
    
            var raspuns_PasParameter = raspuns_Pas != null ?
                new ObjectParameter("Raspuns_Pas", raspuns_Pas) :
                new ObjectParameter("Raspuns_Pas", typeof(string));
    
            var referinta_Raspuns_PasParameter = referinta_Raspuns_Pas != null ?
                new ObjectParameter("Referinta_Raspuns_Pas", referinta_Raspuns_Pas) :
                new ObjectParameter("Referinta_Raspuns_Pas", typeof(string));
    
            var cod_Raspuns_PasParameter = cod_Raspuns_Pas.HasValue ?
                new ObjectParameter("Cod_Raspuns_Pas", cod_Raspuns_Pas) :
                new ObjectParameter("Cod_Raspuns_Pas", typeof(int));
    
            var detalii_Raspuns_PasParameter = detalii_Raspuns_Pas != null ?
                new ObjectParameter("Detalii_Raspuns_Pas", detalii_Raspuns_Pas) :
                new ObjectParameter("Detalii_Raspuns_Pas", typeof(string));
    
            var nivel_Financiar_SubiectParameter = nivel_Financiar_Subiect.HasValue ?
                new ObjectParameter("Nivel_Financiar_Subiect", nivel_Financiar_Subiect) :
                new ObjectParameter("Nivel_Financiar_Subiect", typeof(decimal));
    
            var timp_Afectat_Subiect_PasParameter = timp_Afectat_Subiect_Pas.HasValue ?
                new ObjectParameter("Timp_Afectat_Subiect_Pas", timp_Afectat_Subiect_Pas) :
                new ObjectParameter("Timp_Afectat_Subiect_Pas", typeof(int));
    
            var obstacol_PasParameter = obstacol_Pas != null ?
                new ObjectParameter("Obstacol_Pas", obstacol_Pas) :
                new ObjectParameter("Obstacol_Pas", typeof(string));
    
            var cod_Obstacol_PasParameter = cod_Obstacol_Pas.HasValue ?
                new ObjectParameter("Cod_Obstacol_Pas", cod_Obstacol_Pas) :
                new ObjectParameter("Cod_Obstacol_Pas", typeof(int));
    
            var comentariu_Obstacol_PasParameter = comentariu_Obstacol_Pas != null ?
                new ObjectParameter("Comentariu_Obstacol_Pas", comentariu_Obstacol_Pas) :
                new ObjectParameter("Comentariu_Obstacol_Pas", typeof(string));
    
            var comentariu_Automat_PasParameter = comentariu_Automat_Pas != null ?
                new ObjectParameter("Comentariu_Automat_Pas", comentariu_Automat_Pas) :
                new ObjectParameter("Comentariu_Automat_Pas", typeof(string));
    
            var info_Tipuri_Produse_CautateParameter = info_Tipuri_Produse_Cautate != null ?
                new ObjectParameter("Info_Tipuri_Produse_Cautate", info_Tipuri_Produse_Cautate) :
                new ObjectParameter("Info_Tipuri_Produse_Cautate", typeof(string));
    
            var info_Detalii_Produse_CautateParameter = info_Detalii_Produse_Cautate != null ?
                new ObjectParameter("Info_Detalii_Produse_Cautate", info_Detalii_Produse_Cautate) :
                new ObjectParameter("Info_Detalii_Produse_Cautate", typeof(string));
    
            var info_FurnizoriParameter = info_Furnizori != null ?
                new ObjectParameter("Info_Furnizori", info_Furnizori) :
                new ObjectParameter("Info_Furnizori", typeof(string));
    
            var info_Furnizor_PrincipalParameter = info_Furnizor_Principal != null ?
                new ObjectParameter("Info_Furnizor_Principal", info_Furnizor_Principal) :
                new ObjectParameter("Info_Furnizor_Principal", typeof(string));
    
            var info_Detalii_FurnizoriParameter = info_Detalii_Furnizori != null ?
                new ObjectParameter("Info_Detalii_Furnizori", info_Detalii_Furnizori) :
                new ObjectParameter("Info_Detalii_Furnizori", typeof(string));
    
            var info_Tip_MotivatiiParameter = info_Tip_Motivatii != null ?
                new ObjectParameter("Info_Tip_Motivatii", info_Tip_Motivatii) :
                new ObjectParameter("Info_Tip_Motivatii", typeof(string));
    
            var info_Detalii_MotivatiiParameter = info_Detalii_Motivatii != null ?
                new ObjectParameter("Info_Detalii_Motivatii", info_Detalii_Motivatii) :
                new ObjectParameter("Info_Detalii_Motivatii", typeof(string));
    
            var info_Alte_InfoParameter = info_Alte_Info != null ?
                new ObjectParameter("Info_Alte_Info", info_Alte_Info) :
                new ObjectParameter("Info_Alte_Info", typeof(string));
    
            var conexe_SubiectParameter = conexe_Subiect != null ?
                new ObjectParameter("Conexe_Subiect", conexe_Subiect) :
                new ObjectParameter("Conexe_Subiect", typeof(string));
    
            var referinta_Conexe_SubiectParameter = referinta_Conexe_Subiect != null ?
                new ObjectParameter("Referinta_Conexe_Subiect", referinta_Conexe_Subiect) :
                new ObjectParameter("Referinta_Conexe_Subiect", typeof(string));
    
            var cod_Conexe_SubiectParameter = cod_Conexe_Subiect.HasValue ?
                new ObjectParameter("Cod_Conexe_Subiect", cod_Conexe_Subiect) :
                new ObjectParameter("Cod_Conexe_Subiect", typeof(int));
    
            var detalii_Conexe_SubiectParameter = detalii_Conexe_Subiect != null ?
                new ObjectParameter("Detalii_Conexe_Subiect", detalii_Conexe_Subiect) :
                new ObjectParameter("Detalii_Conexe_Subiect", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaPasUrmator", id_ProspectParameter, nume_PasParameter, cod_Nume_PasParameter, data_Scadenta_PasParameter, stare_PasParameter, cod_Stare_PasParameter, index_Efectuare_PasParameter, index_Neefectuare_PasParameter, index_Reprogramare_PasParameter, pas_ActivParameter, ora_PasParameter, durata_PasParameter, grad_Realizare_PasParameter, prioritate_PasParameter, raspuns_PasParameter, referinta_Raspuns_PasParameter, cod_Raspuns_PasParameter, detalii_Raspuns_PasParameter, nivel_Financiar_SubiectParameter, timp_Afectat_Subiect_PasParameter, obstacol_PasParameter, cod_Obstacol_PasParameter, comentariu_Obstacol_PasParameter, comentariu_Automat_PasParameter, info_Tipuri_Produse_CautateParameter, info_Detalii_Produse_CautateParameter, info_FurnizoriParameter, info_Furnizor_PrincipalParameter, info_Detalii_FurnizoriParameter, info_Tip_MotivatiiParameter, info_Detalii_MotivatiiParameter, info_Alte_InfoParameter, conexe_SubiectParameter, referinta_Conexe_SubiectParameter, cod_Conexe_SubiectParameter, detalii_Conexe_SubiectParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spAdaugaProspectProfil(string tip_Prospect_PF_PJ, string nume_Prospect, string cod_Prospect, string tara, string domeniu, string cod_Domeniu, Nullable<int> cA_Ultimul_An, Nullable<int> nr_Angajati, string sursa_Info_Prospect, string sursa_Info_Prospect_Alt, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var tip_Prospect_PF_PJParameter = tip_Prospect_PF_PJ != null ?
                new ObjectParameter("Tip_Prospect_PF_PJ", tip_Prospect_PF_PJ) :
                new ObjectParameter("Tip_Prospect_PF_PJ", typeof(string));
    
            var nume_ProspectParameter = nume_Prospect != null ?
                new ObjectParameter("Nume_Prospect", nume_Prospect) :
                new ObjectParameter("Nume_Prospect", typeof(string));
    
            var cod_ProspectParameter = cod_Prospect != null ?
                new ObjectParameter("Cod_Prospect", cod_Prospect) :
                new ObjectParameter("Cod_Prospect", typeof(string));
    
            var taraParameter = tara != null ?
                new ObjectParameter("Tara", tara) :
                new ObjectParameter("Tara", typeof(string));
    
            var domeniuParameter = domeniu != null ?
                new ObjectParameter("Domeniu", domeniu) :
                new ObjectParameter("Domeniu", typeof(string));
    
            var cod_DomeniuParameter = cod_Domeniu != null ?
                new ObjectParameter("Cod_Domeniu", cod_Domeniu) :
                new ObjectParameter("Cod_Domeniu", typeof(string));
    
            var cA_Ultimul_AnParameter = cA_Ultimul_An.HasValue ?
                new ObjectParameter("CA_Ultimul_An", cA_Ultimul_An) :
                new ObjectParameter("CA_Ultimul_An", typeof(int));
    
            var nr_AngajatiParameter = nr_Angajati.HasValue ?
                new ObjectParameter("Nr_Angajati", nr_Angajati) :
                new ObjectParameter("Nr_Angajati", typeof(int));
    
            var sursa_Info_ProspectParameter = sursa_Info_Prospect != null ?
                new ObjectParameter("Sursa_Info_Prospect", sursa_Info_Prospect) :
                new ObjectParameter("Sursa_Info_Prospect", typeof(string));
    
            var sursa_Info_Prospect_AltParameter = sursa_Info_Prospect_Alt != null ?
                new ObjectParameter("Sursa_Info_Prospect_Alt", sursa_Info_Prospect_Alt) :
                new ObjectParameter("Sursa_Info_Prospect_Alt", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaProspectProfil", tip_Prospect_PF_PJParameter, nume_ProspectParameter, cod_ProspectParameter, taraParameter, domeniuParameter, cod_DomeniuParameter, cA_Ultimul_AnParameter, nr_AngajatiParameter, sursa_Info_ProspectParameter, sursa_Info_Prospect_AltParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spEditeazaDataScadentaPasi(Nullable<int> iDparam, Nullable<System.DateTime> data_Scadenta_Pas, Nullable<byte> ora_Pas, Nullable<byte> durata_Pas, string id_User)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var data_Scadenta_PasParameter = data_Scadenta_Pas.HasValue ?
                new ObjectParameter("Data_Scadenta_Pas", data_Scadenta_Pas) :
                new ObjectParameter("Data_Scadenta_Pas", typeof(System.DateTime));
    
            var ora_PasParameter = ora_Pas.HasValue ?
                new ObjectParameter("Ora_Pas", ora_Pas) :
                new ObjectParameter("Ora_Pas", typeof(byte));
    
            var durata_PasParameter = durata_Pas.HasValue ?
                new ObjectParameter("Durata_Pas", durata_Pas) :
                new ObjectParameter("Durata_Pas", typeof(byte));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaDataScadentaPasi", iDparamParameter, data_Scadenta_PasParameter, ora_PasParameter, durata_PasParameter, id_UserParameter);
        }
    
        public virtual int spEditeazaDinamicCampProspect(string idName, Nullable<int> idValue, string typeField, string fieldName, string fieldValue, string fieldFileName)
        {
            var idNameParameter = idName != null ?
                new ObjectParameter("IdName", idName) :
                new ObjectParameter("IdName", typeof(string));
    
            var idValueParameter = idValue.HasValue ?
                new ObjectParameter("IdValue", idValue) :
                new ObjectParameter("IdValue", typeof(int));
    
            var typeFieldParameter = typeField != null ?
                new ObjectParameter("TypeField", typeField) :
                new ObjectParameter("TypeField", typeof(string));
    
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var fieldValueParameter = fieldValue != null ?
                new ObjectParameter("FieldValue", fieldValue) :
                new ObjectParameter("FieldValue", typeof(string));
    
            var fieldFileNameParameter = fieldFileName != null ?
                new ObjectParameter("FieldFileName", fieldFileName) :
                new ObjectParameter("FieldFileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaDinamicCampProspect", idNameParameter, idValueParameter, typeFieldParameter, fieldNameParameter, fieldValueParameter, fieldFileNameParameter);
        }
    
        public virtual int spEditeazaProspectAdresa(Nullable<int> iDparam, string regiune_Reper, string cod_Postal, string adresa_Numar, string adresa_Strada, string adresa_Oras, string adresa_Unitate_Regionala, string adresa_SubUnitate_Regionala, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var regiune_ReperParameter = regiune_Reper != null ?
                new ObjectParameter("Regiune_Reper", regiune_Reper) :
                new ObjectParameter("Regiune_Reper", typeof(string));
    
            var cod_PostalParameter = cod_Postal != null ?
                new ObjectParameter("Cod_Postal", cod_Postal) :
                new ObjectParameter("Cod_Postal", typeof(string));
    
            var adresa_NumarParameter = adresa_Numar != null ?
                new ObjectParameter("Adresa_Numar", adresa_Numar) :
                new ObjectParameter("Adresa_Numar", typeof(string));
    
            var adresa_StradaParameter = adresa_Strada != null ?
                new ObjectParameter("Adresa_Strada", adresa_Strada) :
                new ObjectParameter("Adresa_Strada", typeof(string));
    
            var adresa_OrasParameter = adresa_Oras != null ?
                new ObjectParameter("Adresa_Oras", adresa_Oras) :
                new ObjectParameter("Adresa_Oras", typeof(string));
    
            var adresa_Unitate_RegionalaParameter = adresa_Unitate_Regionala != null ?
                new ObjectParameter("Adresa_Unitate_Regionala", adresa_Unitate_Regionala) :
                new ObjectParameter("Adresa_Unitate_Regionala", typeof(string));
    
            var adresa_SubUnitate_RegionalaParameter = adresa_SubUnitate_Regionala != null ?
                new ObjectParameter("Adresa_SubUnitate_Regionala", adresa_SubUnitate_Regionala) :
                new ObjectParameter("Adresa_SubUnitate_Regionala", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaProspectAdresa", iDparamParameter, regiune_ReperParameter, cod_PostalParameter, adresa_NumarParameter, adresa_StradaParameter, adresa_OrasParameter, adresa_Unitate_RegionalaParameter, adresa_SubUnitate_RegionalaParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spEditeazaProspectPasi(Nullable<int> iDparam, Nullable<int> id_Prospect, string nume_Pas, Nullable<int> cod_Nume_Pas, Nullable<System.DateTime> data_Scadenta_Pas, string stare_Pas, Nullable<int> cod_Stare_Pas, Nullable<int> index_Efectuare_Pas, Nullable<int> index_Neefectuare_Pas, Nullable<int> index_Reprogramare_Pas, Nullable<bool> pas_Activ, Nullable<byte> ora_Pas, Nullable<byte> durata_Pas, Nullable<decimal> grad_Realizare_Pas, Nullable<byte> prioritate_Pas, string raspuns_Pas, string referinta_Raspuns_Pas, Nullable<int> cod_Raspuns_Pas, string detalii_Raspuns_Pas, Nullable<decimal> nivel_Financiar_Subiect, Nullable<int> timp_Afectat_Subiect_Pas, string obstacol_Pas, Nullable<int> cod_Obstacol_Pas, string comentariu_Obstacol_Pas, string comentariu_Automat_Pas, string info_Tipuri_Produse_Cautate, string info_Detalii_Produse_Cautate, string info_Furnizori, string info_Furnizor_Principal, string info_Detalii_Furnizori, string info_Tip_Motivatii, string info_Detalii_Motivatii, string info_Alte_Info, string conexe_Subiect, string referinta_Conexe_Subiect, Nullable<int> cod_Conexe_Subiect, string detalii_Conexe_Subiect, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var id_ProspectParameter = id_Prospect.HasValue ?
                new ObjectParameter("Id_Prospect", id_Prospect) :
                new ObjectParameter("Id_Prospect", typeof(int));
    
            var nume_PasParameter = nume_Pas != null ?
                new ObjectParameter("Nume_Pas", nume_Pas) :
                new ObjectParameter("Nume_Pas", typeof(string));
    
            var cod_Nume_PasParameter = cod_Nume_Pas.HasValue ?
                new ObjectParameter("Cod_Nume_Pas", cod_Nume_Pas) :
                new ObjectParameter("Cod_Nume_Pas", typeof(int));
    
            var data_Scadenta_PasParameter = data_Scadenta_Pas.HasValue ?
                new ObjectParameter("Data_Scadenta_Pas", data_Scadenta_Pas) :
                new ObjectParameter("Data_Scadenta_Pas", typeof(System.DateTime));
    
            var stare_PasParameter = stare_Pas != null ?
                new ObjectParameter("Stare_Pas", stare_Pas) :
                new ObjectParameter("Stare_Pas", typeof(string));
    
            var cod_Stare_PasParameter = cod_Stare_Pas.HasValue ?
                new ObjectParameter("Cod_Stare_Pas", cod_Stare_Pas) :
                new ObjectParameter("Cod_Stare_Pas", typeof(int));
    
            var index_Efectuare_PasParameter = index_Efectuare_Pas.HasValue ?
                new ObjectParameter("Index_Efectuare_Pas", index_Efectuare_Pas) :
                new ObjectParameter("Index_Efectuare_Pas", typeof(int));
    
            var index_Neefectuare_PasParameter = index_Neefectuare_Pas.HasValue ?
                new ObjectParameter("Index_Neefectuare_Pas", index_Neefectuare_Pas) :
                new ObjectParameter("Index_Neefectuare_Pas", typeof(int));
    
            var index_Reprogramare_PasParameter = index_Reprogramare_Pas.HasValue ?
                new ObjectParameter("Index_Reprogramare_Pas", index_Reprogramare_Pas) :
                new ObjectParameter("Index_Reprogramare_Pas", typeof(int));
    
            var pas_ActivParameter = pas_Activ.HasValue ?
                new ObjectParameter("Pas_Activ", pas_Activ) :
                new ObjectParameter("Pas_Activ", typeof(bool));
    
            var ora_PasParameter = ora_Pas.HasValue ?
                new ObjectParameter("Ora_Pas", ora_Pas) :
                new ObjectParameter("Ora_Pas", typeof(byte));
    
            var durata_PasParameter = durata_Pas.HasValue ?
                new ObjectParameter("Durata_Pas", durata_Pas) :
                new ObjectParameter("Durata_Pas", typeof(byte));
    
            var grad_Realizare_PasParameter = grad_Realizare_Pas.HasValue ?
                new ObjectParameter("Grad_Realizare_Pas", grad_Realizare_Pas) :
                new ObjectParameter("Grad_Realizare_Pas", typeof(decimal));
    
            var prioritate_PasParameter = prioritate_Pas.HasValue ?
                new ObjectParameter("Prioritate_Pas", prioritate_Pas) :
                new ObjectParameter("Prioritate_Pas", typeof(byte));
    
            var raspuns_PasParameter = raspuns_Pas != null ?
                new ObjectParameter("Raspuns_Pas", raspuns_Pas) :
                new ObjectParameter("Raspuns_Pas", typeof(string));
    
            var referinta_Raspuns_PasParameter = referinta_Raspuns_Pas != null ?
                new ObjectParameter("Referinta_Raspuns_Pas", referinta_Raspuns_Pas) :
                new ObjectParameter("Referinta_Raspuns_Pas", typeof(string));
    
            var cod_Raspuns_PasParameter = cod_Raspuns_Pas.HasValue ?
                new ObjectParameter("Cod_Raspuns_Pas", cod_Raspuns_Pas) :
                new ObjectParameter("Cod_Raspuns_Pas", typeof(int));
    
            var detalii_Raspuns_PasParameter = detalii_Raspuns_Pas != null ?
                new ObjectParameter("Detalii_Raspuns_Pas", detalii_Raspuns_Pas) :
                new ObjectParameter("Detalii_Raspuns_Pas", typeof(string));
    
            var nivel_Financiar_SubiectParameter = nivel_Financiar_Subiect.HasValue ?
                new ObjectParameter("Nivel_Financiar_Subiect", nivel_Financiar_Subiect) :
                new ObjectParameter("Nivel_Financiar_Subiect", typeof(decimal));
    
            var timp_Afectat_Subiect_PasParameter = timp_Afectat_Subiect_Pas.HasValue ?
                new ObjectParameter("Timp_Afectat_Subiect_Pas", timp_Afectat_Subiect_Pas) :
                new ObjectParameter("Timp_Afectat_Subiect_Pas", typeof(int));
    
            var obstacol_PasParameter = obstacol_Pas != null ?
                new ObjectParameter("Obstacol_Pas", obstacol_Pas) :
                new ObjectParameter("Obstacol_Pas", typeof(string));
    
            var cod_Obstacol_PasParameter = cod_Obstacol_Pas.HasValue ?
                new ObjectParameter("Cod_Obstacol_Pas", cod_Obstacol_Pas) :
                new ObjectParameter("Cod_Obstacol_Pas", typeof(int));
    
            var comentariu_Obstacol_PasParameter = comentariu_Obstacol_Pas != null ?
                new ObjectParameter("Comentariu_Obstacol_Pas", comentariu_Obstacol_Pas) :
                new ObjectParameter("Comentariu_Obstacol_Pas", typeof(string));
    
            var comentariu_Automat_PasParameter = comentariu_Automat_Pas != null ?
                new ObjectParameter("Comentariu_Automat_Pas", comentariu_Automat_Pas) :
                new ObjectParameter("Comentariu_Automat_Pas", typeof(string));
    
            var info_Tipuri_Produse_CautateParameter = info_Tipuri_Produse_Cautate != null ?
                new ObjectParameter("Info_Tipuri_Produse_Cautate", info_Tipuri_Produse_Cautate) :
                new ObjectParameter("Info_Tipuri_Produse_Cautate", typeof(string));
    
            var info_Detalii_Produse_CautateParameter = info_Detalii_Produse_Cautate != null ?
                new ObjectParameter("Info_Detalii_Produse_Cautate", info_Detalii_Produse_Cautate) :
                new ObjectParameter("Info_Detalii_Produse_Cautate", typeof(string));
    
            var info_FurnizoriParameter = info_Furnizori != null ?
                new ObjectParameter("Info_Furnizori", info_Furnizori) :
                new ObjectParameter("Info_Furnizori", typeof(string));
    
            var info_Furnizor_PrincipalParameter = info_Furnizor_Principal != null ?
                new ObjectParameter("Info_Furnizor_Principal", info_Furnizor_Principal) :
                new ObjectParameter("Info_Furnizor_Principal", typeof(string));
    
            var info_Detalii_FurnizoriParameter = info_Detalii_Furnizori != null ?
                new ObjectParameter("Info_Detalii_Furnizori", info_Detalii_Furnizori) :
                new ObjectParameter("Info_Detalii_Furnizori", typeof(string));
    
            var info_Tip_MotivatiiParameter = info_Tip_Motivatii != null ?
                new ObjectParameter("Info_Tip_Motivatii", info_Tip_Motivatii) :
                new ObjectParameter("Info_Tip_Motivatii", typeof(string));
    
            var info_Detalii_MotivatiiParameter = info_Detalii_Motivatii != null ?
                new ObjectParameter("Info_Detalii_Motivatii", info_Detalii_Motivatii) :
                new ObjectParameter("Info_Detalii_Motivatii", typeof(string));
    
            var info_Alte_InfoParameter = info_Alte_Info != null ?
                new ObjectParameter("Info_Alte_Info", info_Alte_Info) :
                new ObjectParameter("Info_Alte_Info", typeof(string));
    
            var conexe_SubiectParameter = conexe_Subiect != null ?
                new ObjectParameter("Conexe_Subiect", conexe_Subiect) :
                new ObjectParameter("Conexe_Subiect", typeof(string));
    
            var referinta_Conexe_SubiectParameter = referinta_Conexe_Subiect != null ?
                new ObjectParameter("Referinta_Conexe_Subiect", referinta_Conexe_Subiect) :
                new ObjectParameter("Referinta_Conexe_Subiect", typeof(string));
    
            var cod_Conexe_SubiectParameter = cod_Conexe_Subiect.HasValue ?
                new ObjectParameter("Cod_Conexe_Subiect", cod_Conexe_Subiect) :
                new ObjectParameter("Cod_Conexe_Subiect", typeof(int));
    
            var detalii_Conexe_SubiectParameter = detalii_Conexe_Subiect != null ?
                new ObjectParameter("Detalii_Conexe_Subiect", detalii_Conexe_Subiect) :
                new ObjectParameter("Detalii_Conexe_Subiect", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaProspectPasi", iDparamParameter, id_ProspectParameter, nume_PasParameter, cod_Nume_PasParameter, data_Scadenta_PasParameter, stare_PasParameter, cod_Stare_PasParameter, index_Efectuare_PasParameter, index_Neefectuare_PasParameter, index_Reprogramare_PasParameter, pas_ActivParameter, ora_PasParameter, durata_PasParameter, grad_Realizare_PasParameter, prioritate_PasParameter, raspuns_PasParameter, referinta_Raspuns_PasParameter, cod_Raspuns_PasParameter, detalii_Raspuns_PasParameter, nivel_Financiar_SubiectParameter, timp_Afectat_Subiect_PasParameter, obstacol_PasParameter, cod_Obstacol_PasParameter, comentariu_Obstacol_PasParameter, comentariu_Automat_PasParameter, info_Tipuri_Produse_CautateParameter, info_Detalii_Produse_CautateParameter, info_FurnizoriParameter, info_Furnizor_PrincipalParameter, info_Detalii_FurnizoriParameter, info_Tip_MotivatiiParameter, info_Detalii_MotivatiiParameter, info_Alte_InfoParameter, conexe_SubiectParameter, referinta_Conexe_SubiectParameter, cod_Conexe_SubiectParameter, detalii_Conexe_SubiectParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spEditeazaProspectPD(Nullable<int> iDparam, string persoana_Decizie_Nume, string persoana_Decizie_Prenume, string telefon, string email, string persoana_Decizie_Functie, string persoana_Decizie_Sex, string persoana_Decizie_Nume_Alt, string persoana_Decizie_Prenume_Alt, string telefon_Alt, string email_Alt, string comentariu_Date_Contact, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif, string telefon_Secretariat_1, string telefon_Secretariat_2, string telefon_Secretariat_3, string email_Office, string persoana_Decizie_PD2, string telefon_PD2, string email_PD2, string persoana_Decizie_Nume_PD2, string persoana_Decizie_Prenume_PD2, string persoana_Decizie_Nume_Alt_PD2, string persoana_Decizie_Prenume_Alt_PD2, string persoana_Decizie_Sex_PD2, string persoana_Decizie_Functie_PD2, string telefon_Alt_PD2, string email_Alt_PD2, string persoana_Decizie_PD3, string telefon_PD3, string email_PD3, string persoana_Decizie_Nume_PD3, string persoana_Decizie_Prenume_PD3, string persoana_Decizie_Nume_Alt_PD3, string persoana_Decizie_Prenume_Alt_PD3, string persoana_Decizie_Sex_PD3, string persoana_Decizie_Functie_PD3, string telefon_Alt_PD3, string email_Alt_PD3, string comentariu_Date_Contact_1, string comentariu_Date_Contact_2, string comentariu_Date_Contact_3)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var persoana_Decizie_NumeParameter = persoana_Decizie_Nume != null ?
                new ObjectParameter("Persoana_Decizie_Nume", persoana_Decizie_Nume) :
                new ObjectParameter("Persoana_Decizie_Nume", typeof(string));
    
            var persoana_Decizie_PrenumeParameter = persoana_Decizie_Prenume != null ?
                new ObjectParameter("Persoana_Decizie_Prenume", persoana_Decizie_Prenume) :
                new ObjectParameter("Persoana_Decizie_Prenume", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var persoana_Decizie_FunctieParameter = persoana_Decizie_Functie != null ?
                new ObjectParameter("Persoana_Decizie_Functie", persoana_Decizie_Functie) :
                new ObjectParameter("Persoana_Decizie_Functie", typeof(string));
    
            var persoana_Decizie_SexParameter = persoana_Decizie_Sex != null ?
                new ObjectParameter("Persoana_Decizie_Sex", persoana_Decizie_Sex) :
                new ObjectParameter("Persoana_Decizie_Sex", typeof(string));
    
            var persoana_Decizie_Nume_AltParameter = persoana_Decizie_Nume_Alt != null ?
                new ObjectParameter("Persoana_Decizie_Nume_Alt", persoana_Decizie_Nume_Alt) :
                new ObjectParameter("Persoana_Decizie_Nume_Alt", typeof(string));
    
            var persoana_Decizie_Prenume_AltParameter = persoana_Decizie_Prenume_Alt != null ?
                new ObjectParameter("Persoana_Decizie_Prenume_Alt", persoana_Decizie_Prenume_Alt) :
                new ObjectParameter("Persoana_Decizie_Prenume_Alt", typeof(string));
    
            var telefon_AltParameter = telefon_Alt != null ?
                new ObjectParameter("Telefon_Alt", telefon_Alt) :
                new ObjectParameter("Telefon_Alt", typeof(string));
    
            var email_AltParameter = email_Alt != null ?
                new ObjectParameter("Email_Alt", email_Alt) :
                new ObjectParameter("Email_Alt", typeof(string));
    
            var comentariu_Date_ContactParameter = comentariu_Date_Contact != null ?
                new ObjectParameter("Comentariu_Date_Contact", comentariu_Date_Contact) :
                new ObjectParameter("Comentariu_Date_Contact", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            var telefon_Secretariat_1Parameter = telefon_Secretariat_1 != null ?
                new ObjectParameter("Telefon_Secretariat_1", telefon_Secretariat_1) :
                new ObjectParameter("Telefon_Secretariat_1", typeof(string));
    
            var telefon_Secretariat_2Parameter = telefon_Secretariat_2 != null ?
                new ObjectParameter("Telefon_Secretariat_2", telefon_Secretariat_2) :
                new ObjectParameter("Telefon_Secretariat_2", typeof(string));
    
            var telefon_Secretariat_3Parameter = telefon_Secretariat_3 != null ?
                new ObjectParameter("Telefon_Secretariat_3", telefon_Secretariat_3) :
                new ObjectParameter("Telefon_Secretariat_3", typeof(string));
    
            var email_OfficeParameter = email_Office != null ?
                new ObjectParameter("Email_Office", email_Office) :
                new ObjectParameter("Email_Office", typeof(string));
    
            var persoana_Decizie_PD2Parameter = persoana_Decizie_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_PD2", persoana_Decizie_PD2) :
                new ObjectParameter("Persoana_Decizie_PD2", typeof(string));
    
            var telefon_PD2Parameter = telefon_PD2 != null ?
                new ObjectParameter("Telefon_PD2", telefon_PD2) :
                new ObjectParameter("Telefon_PD2", typeof(string));
    
            var email_PD2Parameter = email_PD2 != null ?
                new ObjectParameter("Email_PD2", email_PD2) :
                new ObjectParameter("Email_PD2", typeof(string));
    
            var persoana_Decizie_Nume_PD2Parameter = persoana_Decizie_Nume_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Nume_PD2", persoana_Decizie_Nume_PD2) :
                new ObjectParameter("Persoana_Decizie_Nume_PD2", typeof(string));
    
            var persoana_Decizie_Prenume_PD2Parameter = persoana_Decizie_Prenume_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Prenume_PD2", persoana_Decizie_Prenume_PD2) :
                new ObjectParameter("Persoana_Decizie_Prenume_PD2", typeof(string));
    
            var persoana_Decizie_Nume_Alt_PD2Parameter = persoana_Decizie_Nume_Alt_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Nume_Alt_PD2", persoana_Decizie_Nume_Alt_PD2) :
                new ObjectParameter("Persoana_Decizie_Nume_Alt_PD2", typeof(string));
    
            var persoana_Decizie_Prenume_Alt_PD2Parameter = persoana_Decizie_Prenume_Alt_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Prenume_Alt_PD2", persoana_Decizie_Prenume_Alt_PD2) :
                new ObjectParameter("Persoana_Decizie_Prenume_Alt_PD2", typeof(string));
    
            var persoana_Decizie_Sex_PD2Parameter = persoana_Decizie_Sex_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Sex_PD2", persoana_Decizie_Sex_PD2) :
                new ObjectParameter("Persoana_Decizie_Sex_PD2", typeof(string));
    
            var persoana_Decizie_Functie_PD2Parameter = persoana_Decizie_Functie_PD2 != null ?
                new ObjectParameter("Persoana_Decizie_Functie_PD2", persoana_Decizie_Functie_PD2) :
                new ObjectParameter("Persoana_Decizie_Functie_PD2", typeof(string));
    
            var telefon_Alt_PD2Parameter = telefon_Alt_PD2 != null ?
                new ObjectParameter("Telefon_Alt_PD2", telefon_Alt_PD2) :
                new ObjectParameter("Telefon_Alt_PD2", typeof(string));
    
            var email_Alt_PD2Parameter = email_Alt_PD2 != null ?
                new ObjectParameter("Email_Alt_PD2", email_Alt_PD2) :
                new ObjectParameter("Email_Alt_PD2", typeof(string));
    
            var persoana_Decizie_PD3Parameter = persoana_Decizie_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_PD3", persoana_Decizie_PD3) :
                new ObjectParameter("Persoana_Decizie_PD3", typeof(string));
    
            var telefon_PD3Parameter = telefon_PD3 != null ?
                new ObjectParameter("Telefon_PD3", telefon_PD3) :
                new ObjectParameter("Telefon_PD3", typeof(string));
    
            var email_PD3Parameter = email_PD3 != null ?
                new ObjectParameter("Email_PD3", email_PD3) :
                new ObjectParameter("Email_PD3", typeof(string));
    
            var persoana_Decizie_Nume_PD3Parameter = persoana_Decizie_Nume_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Nume_PD3", persoana_Decizie_Nume_PD3) :
                new ObjectParameter("Persoana_Decizie_Nume_PD3", typeof(string));
    
            var persoana_Decizie_Prenume_PD3Parameter = persoana_Decizie_Prenume_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Prenume_PD3", persoana_Decizie_Prenume_PD3) :
                new ObjectParameter("Persoana_Decizie_Prenume_PD3", typeof(string));
    
            var persoana_Decizie_Nume_Alt_PD3Parameter = persoana_Decizie_Nume_Alt_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Nume_Alt_PD3", persoana_Decizie_Nume_Alt_PD3) :
                new ObjectParameter("Persoana_Decizie_Nume_Alt_PD3", typeof(string));
    
            var persoana_Decizie_Prenume_Alt_PD3Parameter = persoana_Decizie_Prenume_Alt_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Prenume_Alt_PD3", persoana_Decizie_Prenume_Alt_PD3) :
                new ObjectParameter("Persoana_Decizie_Prenume_Alt_PD3", typeof(string));
    
            var persoana_Decizie_Sex_PD3Parameter = persoana_Decizie_Sex_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Sex_PD3", persoana_Decizie_Sex_PD3) :
                new ObjectParameter("Persoana_Decizie_Sex_PD3", typeof(string));
    
            var persoana_Decizie_Functie_PD3Parameter = persoana_Decizie_Functie_PD3 != null ?
                new ObjectParameter("Persoana_Decizie_Functie_PD3", persoana_Decizie_Functie_PD3) :
                new ObjectParameter("Persoana_Decizie_Functie_PD3", typeof(string));
    
            var telefon_Alt_PD3Parameter = telefon_Alt_PD3 != null ?
                new ObjectParameter("Telefon_Alt_PD3", telefon_Alt_PD3) :
                new ObjectParameter("Telefon_Alt_PD3", typeof(string));
    
            var email_Alt_PD3Parameter = email_Alt_PD3 != null ?
                new ObjectParameter("Email_Alt_PD3", email_Alt_PD3) :
                new ObjectParameter("Email_Alt_PD3", typeof(string));
    
            var comentariu_Date_Contact_1Parameter = comentariu_Date_Contact_1 != null ?
                new ObjectParameter("Comentariu_Date_Contact_1", comentariu_Date_Contact_1) :
                new ObjectParameter("Comentariu_Date_Contact_1", typeof(string));
    
            var comentariu_Date_Contact_2Parameter = comentariu_Date_Contact_2 != null ?
                new ObjectParameter("Comentariu_Date_Contact_2", comentariu_Date_Contact_2) :
                new ObjectParameter("Comentariu_Date_Contact_2", typeof(string));
    
            var comentariu_Date_Contact_3Parameter = comentariu_Date_Contact_3 != null ?
                new ObjectParameter("Comentariu_Date_Contact_3", comentariu_Date_Contact_3) :
                new ObjectParameter("Comentariu_Date_Contact_3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaProspectPD", iDparamParameter, persoana_Decizie_NumeParameter, persoana_Decizie_PrenumeParameter, telefonParameter, emailParameter, persoana_Decizie_FunctieParameter, persoana_Decizie_SexParameter, persoana_Decizie_Nume_AltParameter, persoana_Decizie_Prenume_AltParameter, telefon_AltParameter, email_AltParameter, comentariu_Date_ContactParameter, id_UserParameter, data_IntroParameter, data_ModifParameter, telefon_Secretariat_1Parameter, telefon_Secretariat_2Parameter, telefon_Secretariat_3Parameter, email_OfficeParameter, persoana_Decizie_PD2Parameter, telefon_PD2Parameter, email_PD2Parameter, persoana_Decizie_Nume_PD2Parameter, persoana_Decizie_Prenume_PD2Parameter, persoana_Decizie_Nume_Alt_PD2Parameter, persoana_Decizie_Prenume_Alt_PD2Parameter, persoana_Decizie_Sex_PD2Parameter, persoana_Decizie_Functie_PD2Parameter, telefon_Alt_PD2Parameter, email_Alt_PD2Parameter, persoana_Decizie_PD3Parameter, telefon_PD3Parameter, email_PD3Parameter, persoana_Decizie_Nume_PD3Parameter, persoana_Decizie_Prenume_PD3Parameter, persoana_Decizie_Nume_Alt_PD3Parameter, persoana_Decizie_Prenume_Alt_PD3Parameter, persoana_Decizie_Sex_PD3Parameter, persoana_Decizie_Functie_PD3Parameter, telefon_Alt_PD3Parameter, email_Alt_PD3Parameter, comentariu_Date_Contact_1Parameter, comentariu_Date_Contact_2Parameter, comentariu_Date_Contact_3Parameter);
        }
    
        public virtual int spEditeazaProspectProfil(Nullable<int> iDparam, string tip_Prospect_PF_PJ, string nume_Prospect, string cod_Prospect, string tara, string domeniu, string cod_Domeniu, Nullable<decimal> cA_Ultimul_An, Nullable<int> nr_Angajati, string sursa_Info_Prospect, string sursa_Info_Prospect_Alt, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif, Nullable<bool> aprobare_GDPR, string detalii_GDPR, string referinta_GDPR, Nullable<bool> posibilitate_Montaj, string detalii_Tip_Montaj, string referinta_Montaj, Nullable<bool> prospect_Activ, string status_Prospect, Nullable<int> cod_Status_Prospect, string comentariu_Prospect, Nullable<bool> z_Bit_Field, Nullable<int> z_Int_Field, string z_String_Field, string z_Text_Field, string user_Alocat, Nullable<System.DateTime> data_Alocare)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var tip_Prospect_PF_PJParameter = tip_Prospect_PF_PJ != null ?
                new ObjectParameter("Tip_Prospect_PF_PJ", tip_Prospect_PF_PJ) :
                new ObjectParameter("Tip_Prospect_PF_PJ", typeof(string));
    
            var nume_ProspectParameter = nume_Prospect != null ?
                new ObjectParameter("Nume_Prospect", nume_Prospect) :
                new ObjectParameter("Nume_Prospect", typeof(string));
    
            var cod_ProspectParameter = cod_Prospect != null ?
                new ObjectParameter("Cod_Prospect", cod_Prospect) :
                new ObjectParameter("Cod_Prospect", typeof(string));
    
            var taraParameter = tara != null ?
                new ObjectParameter("Tara", tara) :
                new ObjectParameter("Tara", typeof(string));
    
            var domeniuParameter = domeniu != null ?
                new ObjectParameter("Domeniu", domeniu) :
                new ObjectParameter("Domeniu", typeof(string));
    
            var cod_DomeniuParameter = cod_Domeniu != null ?
                new ObjectParameter("Cod_Domeniu", cod_Domeniu) :
                new ObjectParameter("Cod_Domeniu", typeof(string));
    
            var cA_Ultimul_AnParameter = cA_Ultimul_An.HasValue ?
                new ObjectParameter("CA_Ultimul_An", cA_Ultimul_An) :
                new ObjectParameter("CA_Ultimul_An", typeof(decimal));
    
            var nr_AngajatiParameter = nr_Angajati.HasValue ?
                new ObjectParameter("Nr_Angajati", nr_Angajati) :
                new ObjectParameter("Nr_Angajati", typeof(int));
    
            var sursa_Info_ProspectParameter = sursa_Info_Prospect != null ?
                new ObjectParameter("Sursa_Info_Prospect", sursa_Info_Prospect) :
                new ObjectParameter("Sursa_Info_Prospect", typeof(string));
    
            var sursa_Info_Prospect_AltParameter = sursa_Info_Prospect_Alt != null ?
                new ObjectParameter("Sursa_Info_Prospect_Alt", sursa_Info_Prospect_Alt) :
                new ObjectParameter("Sursa_Info_Prospect_Alt", typeof(string));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            var aprobare_GDPRParameter = aprobare_GDPR.HasValue ?
                new ObjectParameter("Aprobare_GDPR", aprobare_GDPR) :
                new ObjectParameter("Aprobare_GDPR", typeof(bool));
    
            var detalii_GDPRParameter = detalii_GDPR != null ?
                new ObjectParameter("Detalii_GDPR", detalii_GDPR) :
                new ObjectParameter("Detalii_GDPR", typeof(string));
    
            var referinta_GDPRParameter = referinta_GDPR != null ?
                new ObjectParameter("Referinta_GDPR", referinta_GDPR) :
                new ObjectParameter("Referinta_GDPR", typeof(string));
    
            var posibilitate_MontajParameter = posibilitate_Montaj.HasValue ?
                new ObjectParameter("Posibilitate_Montaj", posibilitate_Montaj) :
                new ObjectParameter("Posibilitate_Montaj", typeof(bool));
    
            var detalii_Tip_MontajParameter = detalii_Tip_Montaj != null ?
                new ObjectParameter("Detalii_Tip_Montaj", detalii_Tip_Montaj) :
                new ObjectParameter("Detalii_Tip_Montaj", typeof(string));
    
            var referinta_MontajParameter = referinta_Montaj != null ?
                new ObjectParameter("Referinta_Montaj", referinta_Montaj) :
                new ObjectParameter("Referinta_Montaj", typeof(string));
    
            var prospect_ActivParameter = prospect_Activ.HasValue ?
                new ObjectParameter("Prospect_Activ", prospect_Activ) :
                new ObjectParameter("Prospect_Activ", typeof(bool));
    
            var status_ProspectParameter = status_Prospect != null ?
                new ObjectParameter("Status_Prospect", status_Prospect) :
                new ObjectParameter("Status_Prospect", typeof(string));
    
            var cod_Status_ProspectParameter = cod_Status_Prospect.HasValue ?
                new ObjectParameter("Cod_Status_Prospect", cod_Status_Prospect) :
                new ObjectParameter("Cod_Status_Prospect", typeof(int));
    
            var comentariu_ProspectParameter = comentariu_Prospect != null ?
                new ObjectParameter("Comentariu_Prospect", comentariu_Prospect) :
                new ObjectParameter("Comentariu_Prospect", typeof(string));
    
            var z_Bit_FieldParameter = z_Bit_Field.HasValue ?
                new ObjectParameter("Z_Bit_Field", z_Bit_Field) :
                new ObjectParameter("Z_Bit_Field", typeof(bool));
    
            var z_Int_FieldParameter = z_Int_Field.HasValue ?
                new ObjectParameter("Z_Int_Field", z_Int_Field) :
                new ObjectParameter("Z_Int_Field", typeof(int));
    
            var z_String_FieldParameter = z_String_Field != null ?
                new ObjectParameter("Z_String_Field", z_String_Field) :
                new ObjectParameter("Z_String_Field", typeof(string));
    
            var z_Text_FieldParameter = z_Text_Field != null ?
                new ObjectParameter("Z_Text_Field", z_Text_Field) :
                new ObjectParameter("Z_Text_Field", typeof(string));
    
            var user_AlocatParameter = user_Alocat != null ?
                new ObjectParameter("User_Alocat", user_Alocat) :
                new ObjectParameter("User_Alocat", typeof(string));
    
            var data_AlocareParameter = data_Alocare.HasValue ?
                new ObjectParameter("Data_Alocare", data_Alocare) :
                new ObjectParameter("Data_Alocare", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaProspectProfil", iDparamParameter, tip_Prospect_PF_PJParameter, nume_ProspectParameter, cod_ProspectParameter, taraParameter, domeniuParameter, cod_DomeniuParameter, cA_Ultimul_AnParameter, nr_AngajatiParameter, sursa_Info_ProspectParameter, sursa_Info_Prospect_AltParameter, id_UserParameter, data_IntroParameter, data_ModifParameter, aprobare_GDPRParameter, detalii_GDPRParameter, referinta_GDPRParameter, posibilitate_MontajParameter, detalii_Tip_MontajParameter, referinta_MontajParameter, prospect_ActivParameter, status_ProspectParameter, cod_Status_ProspectParameter, comentariu_ProspectParameter, z_Bit_FieldParameter, z_Int_FieldParameter, z_String_FieldParameter, z_Text_FieldParameter, user_AlocatParameter, data_AlocareParameter);
        }
    
        public virtual int spSeteazaActivInactivPasi(Nullable<int> iDparam, Nullable<int> id_Prospect, Nullable<bool> pas_Activ, string id_User, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var id_ProspectParameter = id_Prospect.HasValue ?
                new ObjectParameter("Id_Prospect", id_Prospect) :
                new ObjectParameter("Id_Prospect", typeof(int));
    
            var pas_ActivParameter = pas_Activ.HasValue ?
                new ObjectParameter("Pas_Activ", pas_Activ) :
                new ObjectParameter("Pas_Activ", typeof(bool));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSeteazaActivInactivPasi", iDparamParameter, id_ProspectParameter, pas_ActivParameter, id_UserParameter, data_ModifParameter);
        }
    
        public virtual int spSeteazaActivInactivProspect(Nullable<int> iDparam, Nullable<bool> prospect_Activ, string id_User, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var prospect_ActivParameter = prospect_Activ.HasValue ?
                new ObjectParameter("Prospect_Activ", prospect_Activ) :
                new ObjectParameter("Prospect_Activ", typeof(bool));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSeteazaActivInactivProspect", iDparamParameter, prospect_ActivParameter, id_UserParameter, data_ModifParameter);
        }
    
        public virtual int spStergeProspectID(Nullable<int> iDparam)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spStergeProspectID", iDparamParameter);
        }
    
        public virtual int spTransferProspect(string tipTransfer, Nullable<int> iDparam, string id_User, string user_Alocat)
        {
            var tipTransferParameter = tipTransfer != null ?
                new ObjectParameter("TipTransfer", tipTransfer) :
                new ObjectParameter("TipTransfer", typeof(string));
    
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var user_AlocatParameter = user_Alocat != null ?
                new ObjectParameter("User_Alocat", user_Alocat) :
                new ObjectParameter("User_Alocat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTransferProspect", tipTransferParameter, iDparamParameter, id_UserParameter, user_AlocatParameter);
        }
    
        public virtual int spAdaugaActivitateCurenta(string nume_Activitate, Nullable<int> cod_Activitate, string detalii_Tip_Activitate, string subiect_Activitate, string referinta_Subiect, Nullable<int> cod_Subiect, string detalii_Subiect, Nullable<decimal> nivel_Financiar_Subiect, Nullable<byte> timp_Afectat_Subiect, Nullable<System.DateTime> data_Scadenta, Nullable<byte> ora_Activitate, Nullable<byte> durata_Activitate, Nullable<decimal> grad_Realizare, Nullable<byte> prioritate_Activitate, string stare_Activitate, Nullable<int> cod_Stare_Activitate, string comentariu_Activitate, Nullable<int> index_Reprogramare_Activitate, Nullable<int> index_Amanare_Activitate, Nullable<bool> activitate_Activa, Nullable<bool> z_Bit_Field, Nullable<int> z_Int_Field, string z_String_Field, string z_Text_Field, string user_Alocat, Nullable<System.DateTime> data_Alocare, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var nume_ActivitateParameter = nume_Activitate != null ?
                new ObjectParameter("Nume_Activitate", nume_Activitate) :
                new ObjectParameter("Nume_Activitate", typeof(string));
    
            var cod_ActivitateParameter = cod_Activitate.HasValue ?
                new ObjectParameter("Cod_Activitate", cod_Activitate) :
                new ObjectParameter("Cod_Activitate", typeof(int));
    
            var detalii_Tip_ActivitateParameter = detalii_Tip_Activitate != null ?
                new ObjectParameter("Detalii_Tip_Activitate", detalii_Tip_Activitate) :
                new ObjectParameter("Detalii_Tip_Activitate", typeof(string));
    
            var subiect_ActivitateParameter = subiect_Activitate != null ?
                new ObjectParameter("Subiect_Activitate", subiect_Activitate) :
                new ObjectParameter("Subiect_Activitate", typeof(string));
    
            var referinta_SubiectParameter = referinta_Subiect != null ?
                new ObjectParameter("Referinta_Subiect", referinta_Subiect) :
                new ObjectParameter("Referinta_Subiect", typeof(string));
    
            var cod_SubiectParameter = cod_Subiect.HasValue ?
                new ObjectParameter("Cod_Subiect", cod_Subiect) :
                new ObjectParameter("Cod_Subiect", typeof(int));
    
            var detalii_SubiectParameter = detalii_Subiect != null ?
                new ObjectParameter("Detalii_Subiect", detalii_Subiect) :
                new ObjectParameter("Detalii_Subiect", typeof(string));
    
            var nivel_Financiar_SubiectParameter = nivel_Financiar_Subiect.HasValue ?
                new ObjectParameter("Nivel_Financiar_Subiect", nivel_Financiar_Subiect) :
                new ObjectParameter("Nivel_Financiar_Subiect", typeof(decimal));
    
            var timp_Afectat_SubiectParameter = timp_Afectat_Subiect.HasValue ?
                new ObjectParameter("Timp_Afectat_Subiect", timp_Afectat_Subiect) :
                new ObjectParameter("Timp_Afectat_Subiect", typeof(byte));
    
            var data_ScadentaParameter = data_Scadenta.HasValue ?
                new ObjectParameter("Data_Scadenta", data_Scadenta) :
                new ObjectParameter("Data_Scadenta", typeof(System.DateTime));
    
            var ora_ActivitateParameter = ora_Activitate.HasValue ?
                new ObjectParameter("Ora_Activitate", ora_Activitate) :
                new ObjectParameter("Ora_Activitate", typeof(byte));
    
            var durata_ActivitateParameter = durata_Activitate.HasValue ?
                new ObjectParameter("Durata_Activitate", durata_Activitate) :
                new ObjectParameter("Durata_Activitate", typeof(byte));
    
            var grad_RealizareParameter = grad_Realizare.HasValue ?
                new ObjectParameter("Grad_Realizare", grad_Realizare) :
                new ObjectParameter("Grad_Realizare", typeof(decimal));
    
            var prioritate_ActivitateParameter = prioritate_Activitate.HasValue ?
                new ObjectParameter("Prioritate_Activitate", prioritate_Activitate) :
                new ObjectParameter("Prioritate_Activitate", typeof(byte));
    
            var stare_ActivitateParameter = stare_Activitate != null ?
                new ObjectParameter("Stare_Activitate", stare_Activitate) :
                new ObjectParameter("Stare_Activitate", typeof(string));
    
            var cod_Stare_ActivitateParameter = cod_Stare_Activitate.HasValue ?
                new ObjectParameter("Cod_Stare_Activitate", cod_Stare_Activitate) :
                new ObjectParameter("Cod_Stare_Activitate", typeof(int));
    
            var comentariu_ActivitateParameter = comentariu_Activitate != null ?
                new ObjectParameter("Comentariu_Activitate", comentariu_Activitate) :
                new ObjectParameter("Comentariu_Activitate", typeof(string));
    
            var index_Reprogramare_ActivitateParameter = index_Reprogramare_Activitate.HasValue ?
                new ObjectParameter("Index_Reprogramare_Activitate", index_Reprogramare_Activitate) :
                new ObjectParameter("Index_Reprogramare_Activitate", typeof(int));
    
            var index_Amanare_ActivitateParameter = index_Amanare_Activitate.HasValue ?
                new ObjectParameter("Index_Amanare_Activitate", index_Amanare_Activitate) :
                new ObjectParameter("Index_Amanare_Activitate", typeof(int));
    
            var activitate_ActivaParameter = activitate_Activa.HasValue ?
                new ObjectParameter("Activitate_Activa", activitate_Activa) :
                new ObjectParameter("Activitate_Activa", typeof(bool));
    
            var z_Bit_FieldParameter = z_Bit_Field.HasValue ?
                new ObjectParameter("Z_Bit_Field", z_Bit_Field) :
                new ObjectParameter("Z_Bit_Field", typeof(bool));
    
            var z_Int_FieldParameter = z_Int_Field.HasValue ?
                new ObjectParameter("Z_Int_Field", z_Int_Field) :
                new ObjectParameter("Z_Int_Field", typeof(int));
    
            var z_String_FieldParameter = z_String_Field != null ?
                new ObjectParameter("Z_String_Field", z_String_Field) :
                new ObjectParameter("Z_String_Field", typeof(string));
    
            var z_Text_FieldParameter = z_Text_Field != null ?
                new ObjectParameter("Z_Text_Field", z_Text_Field) :
                new ObjectParameter("Z_Text_Field", typeof(string));
    
            var user_AlocatParameter = user_Alocat != null ?
                new ObjectParameter("User_Alocat", user_Alocat) :
                new ObjectParameter("User_Alocat", typeof(string));
    
            var data_AlocareParameter = data_Alocare.HasValue ?
                new ObjectParameter("Data_Alocare", data_Alocare) :
                new ObjectParameter("Data_Alocare", typeof(System.DateTime));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaActivitateCurenta", nume_ActivitateParameter, cod_ActivitateParameter, detalii_Tip_ActivitateParameter, subiect_ActivitateParameter, referinta_SubiectParameter, cod_SubiectParameter, detalii_SubiectParameter, nivel_Financiar_SubiectParameter, timp_Afectat_SubiectParameter, data_ScadentaParameter, ora_ActivitateParameter, durata_ActivitateParameter, grad_RealizareParameter, prioritate_ActivitateParameter, stare_ActivitateParameter, cod_Stare_ActivitateParameter, comentariu_ActivitateParameter, index_Reprogramare_ActivitateParameter, index_Amanare_ActivitateParameter, activitate_ActivaParameter, z_Bit_FieldParameter, z_Int_FieldParameter, z_String_FieldParameter, z_Text_FieldParameter, user_AlocatParameter, data_AlocareParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spEditeazaActivitateCurenta(Nullable<int> iDparam, string nume_Activitate, Nullable<int> cod_Activitate, string detalii_Tip_Activitate, string subiect_Activitate, string referinta_Subiect, Nullable<int> cod_Subiect, string detalii_Subiect, Nullable<decimal> nivel_Financiar_Subiect, Nullable<byte> timp_Afectat_Subiect, Nullable<System.DateTime> data_Scadenta, Nullable<byte> ora_Activitate, Nullable<byte> durata_Activitate, Nullable<decimal> grad_Realizare, Nullable<byte> prioritate_Activitate, string stare_Activitate, Nullable<int> cod_Stare_Activitate, string comentariu_Activitate, Nullable<int> index_Reprogramare_Activitate, Nullable<int> index_Amanare_Activitate, Nullable<bool> activitate_Activa, Nullable<bool> z_Bit_Field, Nullable<int> z_Int_Field, string z_String_Field, string z_Text_Field, string user_Alocat, Nullable<System.DateTime> data_Alocare, string id_User, Nullable<System.DateTime> data_Intro, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var nume_ActivitateParameter = nume_Activitate != null ?
                new ObjectParameter("Nume_Activitate", nume_Activitate) :
                new ObjectParameter("Nume_Activitate", typeof(string));
    
            var cod_ActivitateParameter = cod_Activitate.HasValue ?
                new ObjectParameter("Cod_Activitate", cod_Activitate) :
                new ObjectParameter("Cod_Activitate", typeof(int));
    
            var detalii_Tip_ActivitateParameter = detalii_Tip_Activitate != null ?
                new ObjectParameter("Detalii_Tip_Activitate", detalii_Tip_Activitate) :
                new ObjectParameter("Detalii_Tip_Activitate", typeof(string));
    
            var subiect_ActivitateParameter = subiect_Activitate != null ?
                new ObjectParameter("Subiect_Activitate", subiect_Activitate) :
                new ObjectParameter("Subiect_Activitate", typeof(string));
    
            var referinta_SubiectParameter = referinta_Subiect != null ?
                new ObjectParameter("Referinta_Subiect", referinta_Subiect) :
                new ObjectParameter("Referinta_Subiect", typeof(string));
    
            var cod_SubiectParameter = cod_Subiect.HasValue ?
                new ObjectParameter("Cod_Subiect", cod_Subiect) :
                new ObjectParameter("Cod_Subiect", typeof(int));
    
            var detalii_SubiectParameter = detalii_Subiect != null ?
                new ObjectParameter("Detalii_Subiect", detalii_Subiect) :
                new ObjectParameter("Detalii_Subiect", typeof(string));
    
            var nivel_Financiar_SubiectParameter = nivel_Financiar_Subiect.HasValue ?
                new ObjectParameter("Nivel_Financiar_Subiect", nivel_Financiar_Subiect) :
                new ObjectParameter("Nivel_Financiar_Subiect", typeof(decimal));
    
            var timp_Afectat_SubiectParameter = timp_Afectat_Subiect.HasValue ?
                new ObjectParameter("Timp_Afectat_Subiect", timp_Afectat_Subiect) :
                new ObjectParameter("Timp_Afectat_Subiect", typeof(byte));
    
            var data_ScadentaParameter = data_Scadenta.HasValue ?
                new ObjectParameter("Data_Scadenta", data_Scadenta) :
                new ObjectParameter("Data_Scadenta", typeof(System.DateTime));
    
            var ora_ActivitateParameter = ora_Activitate.HasValue ?
                new ObjectParameter("Ora_Activitate", ora_Activitate) :
                new ObjectParameter("Ora_Activitate", typeof(byte));
    
            var durata_ActivitateParameter = durata_Activitate.HasValue ?
                new ObjectParameter("Durata_Activitate", durata_Activitate) :
                new ObjectParameter("Durata_Activitate", typeof(byte));
    
            var grad_RealizareParameter = grad_Realizare.HasValue ?
                new ObjectParameter("Grad_Realizare", grad_Realizare) :
                new ObjectParameter("Grad_Realizare", typeof(decimal));
    
            var prioritate_ActivitateParameter = prioritate_Activitate.HasValue ?
                new ObjectParameter("Prioritate_Activitate", prioritate_Activitate) :
                new ObjectParameter("Prioritate_Activitate", typeof(byte));
    
            var stare_ActivitateParameter = stare_Activitate != null ?
                new ObjectParameter("Stare_Activitate", stare_Activitate) :
                new ObjectParameter("Stare_Activitate", typeof(string));
    
            var cod_Stare_ActivitateParameter = cod_Stare_Activitate.HasValue ?
                new ObjectParameter("Cod_Stare_Activitate", cod_Stare_Activitate) :
                new ObjectParameter("Cod_Stare_Activitate", typeof(int));
    
            var comentariu_ActivitateParameter = comentariu_Activitate != null ?
                new ObjectParameter("Comentariu_Activitate", comentariu_Activitate) :
                new ObjectParameter("Comentariu_Activitate", typeof(string));
    
            var index_Reprogramare_ActivitateParameter = index_Reprogramare_Activitate.HasValue ?
                new ObjectParameter("Index_Reprogramare_Activitate", index_Reprogramare_Activitate) :
                new ObjectParameter("Index_Reprogramare_Activitate", typeof(int));
    
            var index_Amanare_ActivitateParameter = index_Amanare_Activitate.HasValue ?
                new ObjectParameter("Index_Amanare_Activitate", index_Amanare_Activitate) :
                new ObjectParameter("Index_Amanare_Activitate", typeof(int));
    
            var activitate_ActivaParameter = activitate_Activa.HasValue ?
                new ObjectParameter("Activitate_Activa", activitate_Activa) :
                new ObjectParameter("Activitate_Activa", typeof(bool));
    
            var z_Bit_FieldParameter = z_Bit_Field.HasValue ?
                new ObjectParameter("Z_Bit_Field", z_Bit_Field) :
                new ObjectParameter("Z_Bit_Field", typeof(bool));
    
            var z_Int_FieldParameter = z_Int_Field.HasValue ?
                new ObjectParameter("Z_Int_Field", z_Int_Field) :
                new ObjectParameter("Z_Int_Field", typeof(int));
    
            var z_String_FieldParameter = z_String_Field != null ?
                new ObjectParameter("Z_String_Field", z_String_Field) :
                new ObjectParameter("Z_String_Field", typeof(string));
    
            var z_Text_FieldParameter = z_Text_Field != null ?
                new ObjectParameter("Z_Text_Field", z_Text_Field) :
                new ObjectParameter("Z_Text_Field", typeof(string));
    
            var user_AlocatParameter = user_Alocat != null ?
                new ObjectParameter("User_Alocat", user_Alocat) :
                new ObjectParameter("User_Alocat", typeof(string));
    
            var data_AlocareParameter = data_Alocare.HasValue ?
                new ObjectParameter("Data_Alocare", data_Alocare) :
                new ObjectParameter("Data_Alocare", typeof(System.DateTime));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_IntroParameter = data_Intro.HasValue ?
                new ObjectParameter("Data_Intro", data_Intro) :
                new ObjectParameter("Data_Intro", typeof(System.DateTime));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaActivitateCurenta", iDparamParameter, nume_ActivitateParameter, cod_ActivitateParameter, detalii_Tip_ActivitateParameter, subiect_ActivitateParameter, referinta_SubiectParameter, cod_SubiectParameter, detalii_SubiectParameter, nivel_Financiar_SubiectParameter, timp_Afectat_SubiectParameter, data_ScadentaParameter, ora_ActivitateParameter, durata_ActivitateParameter, grad_RealizareParameter, prioritate_ActivitateParameter, stare_ActivitateParameter, cod_Stare_ActivitateParameter, comentariu_ActivitateParameter, index_Reprogramare_ActivitateParameter, index_Amanare_ActivitateParameter, activitate_ActivaParameter, z_Bit_FieldParameter, z_Int_FieldParameter, z_String_FieldParameter, z_Text_FieldParameter, user_AlocatParameter, data_AlocareParameter, id_UserParameter, data_IntroParameter, data_ModifParameter);
        }
    
        public virtual int spEditeazaDataScadentaActivitate(Nullable<int> iDparam, Nullable<System.DateTime> data_Scadenta, Nullable<byte> ora_Activitate, Nullable<byte> durata_Activitate, string id_User)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var data_ScadentaParameter = data_Scadenta.HasValue ?
                new ObjectParameter("Data_Scadenta", data_Scadenta) :
                new ObjectParameter("Data_Scadenta", typeof(System.DateTime));
    
            var ora_ActivitateParameter = ora_Activitate.HasValue ?
                new ObjectParameter("Ora_Activitate", ora_Activitate) :
                new ObjectParameter("Ora_Activitate", typeof(byte));
    
            var durata_ActivitateParameter = durata_Activitate.HasValue ?
                new ObjectParameter("Durata_Activitate", durata_Activitate) :
                new ObjectParameter("Durata_Activitate", typeof(byte));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaDataScadentaActivitate", iDparamParameter, data_ScadentaParameter, ora_ActivitateParameter, durata_ActivitateParameter, id_UserParameter);
        }
    
        public virtual int spEditeazaDinamicCampActivitate(string idName, Nullable<int> idValue, string typeField, string fieldName, string fieldValue)
        {
            var idNameParameter = idName != null ?
                new ObjectParameter("IdName", idName) :
                new ObjectParameter("IdName", typeof(string));
    
            var idValueParameter = idValue.HasValue ?
                new ObjectParameter("IdValue", idValue) :
                new ObjectParameter("IdValue", typeof(int));
    
            var typeFieldParameter = typeField != null ?
                new ObjectParameter("TypeField", typeField) :
                new ObjectParameter("TypeField", typeof(string));
    
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var fieldValueParameter = fieldValue != null ?
                new ObjectParameter("FieldValue", fieldValue) :
                new ObjectParameter("FieldValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditeazaDinamicCampActivitate", idNameParameter, idValueParameter, typeFieldParameter, fieldNameParameter, fieldValueParameter);
        }
    
        public virtual int spSeteazaActivInactivActivitate(Nullable<int> iDparam, Nullable<bool> activitate_Activa, string id_User, Nullable<System.DateTime> data_Modif)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var activitate_ActivaParameter = activitate_Activa.HasValue ?
                new ObjectParameter("Activitate_Activa", activitate_Activa) :
                new ObjectParameter("Activitate_Activa", typeof(bool));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var data_ModifParameter = data_Modif.HasValue ?
                new ObjectParameter("Data_Modif", data_Modif) :
                new ObjectParameter("Data_Modif", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSeteazaActivInactivActivitate", iDparamParameter, activitate_ActivaParameter, id_UserParameter, data_ModifParameter);
        }
    
        public virtual int spStergeActivitateCurenta(Nullable<int> iDparam)
        {
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spStergeActivitateCurenta", iDparamParameter);
        }
    
        public virtual int spTransferActivitate(string tipTransfer, Nullable<int> iDparam, string id_User, string user_Alocat)
        {
            var tipTransferParameter = tipTransfer != null ?
                new ObjectParameter("TipTransfer", tipTransfer) :
                new ObjectParameter("TipTransfer", typeof(string));
    
            var iDparamParameter = iDparam.HasValue ?
                new ObjectParameter("IDparam", iDparam) :
                new ObjectParameter("IDparam", typeof(int));
    
            var id_UserParameter = id_User != null ?
                new ObjectParameter("Id_User", id_User) :
                new ObjectParameter("Id_User", typeof(string));
    
            var user_AlocatParameter = user_Alocat != null ?
                new ObjectParameter("User_Alocat", user_Alocat) :
                new ObjectParameter("User_Alocat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTransferActivitate", tipTransferParameter, iDparamParameter, id_UserParameter, user_AlocatParameter);
        }
    }
}
