//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predef_Tipuri_Activitati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predef_Tipuri_Activitati()
        {
            this.Predef_SubTipuri_Activitati = new HashSet<Predef_SubTipuri_Activitati>();
        }
    
        public int Id_Act { get; set; }
        public string Nume_Act { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predef_SubTipuri_Activitati> Predef_SubTipuri_Activitati { get; set; }
    }
}
