//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecte_Contact
    {
        public int Id { get; set; }
        public int Id_Prospect { get; set; }
        public string Persoana_Decizie { get; set; }
        public string Telefon { get; set; }
        public string Regiune_Reper { get; set; }
        public string Adresa_Text { get; set; }
        public string Cod_Postal { get; set; }
        public string Email { get; set; }
        public string Web_Site { get; set; }
        public string Adresa_Numar { get; set; }
        public string Adresa_Strada { get; set; }
        public string Adresa_Oras { get; set; }
        public string Adresa_Unitate_Regionala { get; set; }
        public string Adresa_SubUnitate_Regionala { get; set; }
        public string Persoana_Decizie_Nume { get; set; }
        public string Persoana_Decizie_Prenume { get; set; }
        public string Persoana_Decizie_Nume_Alt { get; set; }
        public string Persoana_Decizie_Prenume_Alt { get; set; }
        public string Persoana_Decizie_Sex { get; set; }
        public string Persoana_Decizie_Functie { get; set; }
        public string Telefon_Alt { get; set; }
        public string Email_Alt { get; set; }
        public string Id_User { get; set; }
        public System.DateTime Data_Intro { get; set; }
        public System.DateTime Data_Modif { get; set; }
    }
}
