//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecte_ContactPlus
    {
        public int Id { get; set; }
        public int Id_Prospect { get; set; }
        public string Telefon_Secretariat_1 { get; set; }
        public string Telefon_Secretariat_2 { get; set; }
        public string Telefon_Secretariat_3 { get; set; }
        public string Email_Office { get; set; }
        public string Persoana_Decizie_PD2 { get; set; }
        public string Telefon_PD2 { get; set; }
        public string Email_PD2 { get; set; }
        public string Persoana_Decizie_Nume_PD2 { get; set; }
        public string Persoana_Decizie_Prenume_PD2 { get; set; }
        public string Persoana_Decizie_Nume_Alt_PD2 { get; set; }
        public string Persoana_Decizie_Prenume_Alt_PD2 { get; set; }
        public string Persoana_Decizie_Sex_PD2 { get; set; }
        public string Persoana_Decizie_Functie_PD2 { get; set; }
        public string Telefon_Alt_PD2 { get; set; }
        public string Email_Alt_PD2 { get; set; }
        public string Persoana_Decizie_PD3 { get; set; }
        public string Telefon_PD3 { get; set; }
        public string Email_PD3 { get; set; }
        public string Persoana_Decizie_Nume_PD3 { get; set; }
        public string Persoana_Decizie_Prenume_PD3 { get; set; }
        public string Persoana_Decizie_Nume_Alt_PD3 { get; set; }
        public string Persoana_Decizie_Prenume_Alt_PD3 { get; set; }
        public string Persoana_Decizie_Sex_PD3 { get; set; }
        public string Persoana_Decizie_Functie_PD3 { get; set; }
        public string Telefon_Alt_PD3 { get; set; }
        public string Email_Alt_PD3 { get; set; }
        public string Comentariu_Date_Contact_1 { get; set; }
        public string Comentariu_Date_Contact_2 { get; set; }
        public string Comentariu_Date_Contact_3 { get; set; }
        public string Id_User { get; set; }
        public System.DateTime Data_Intro { get; set; }
        public System.DateTime Data_Modif { get; set; }
    
        public virtual Prospecte_Profil Prospecte_Profil { get; set; }
    }
}
