//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecte_ProfilPlus
    {
        public int Id { get; set; }
        public int Id_Prospect { get; set; }
        public Nullable<bool> Aprobare_GDPR { get; set; }
        public string Detalii_GDPR { get; set; }
        public string Referinta_GDPR { get; set; }
        public Nullable<bool> Posibilitate_Montaj { get; set; }
        public string Detalii_Tip_Montaj { get; set; }
        public string Referinta_Montaj { get; set; }
        public Nullable<bool> Prospect_Activ { get; set; }
        public string Status_Prospect { get; set; }
        public Nullable<int> Cod_Status_Prospect { get; set; }
        public string Comentariu_Prospect { get; set; }
        public Nullable<bool> Z_Bit_Field { get; set; }
        public Nullable<int> Z_Int_Field { get; set; }
        public string Z_String_Field { get; set; }
        public string Z_Text_Field { get; set; }
        public string User_Alocat { get; set; }
        public System.DateTime Data_Alocare { get; set; }
        public string Id_User { get; set; }
        public System.DateTime Data_Intro { get; set; }
        public System.DateTime Data_Modif { get; set; }
    
        public virtual Prospecte_Profil Prospecte_Profil { get; set; }
    }
}
