//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecte_Profil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prospecte_Profil()
        {
            this.Prospecte_ContactPlus = new HashSet<Prospecte_ContactPlus>();
            this.Prospecte_Pasi_Urmatori = new HashSet<Prospecte_Pasi_Urmatori>();
            this.Prospecte_ProfilPlus = new HashSet<Prospecte_ProfilPlus>();
        }
    
        public int Id_Prospect { get; set; }
        public string Tip_Prospect_PF_PJ { get; set; }
        public string Nume_Prospect { get; set; }
        public string Cod_Prospect { get; set; }
        public string Tara { get; set; }
        public string Domeniu { get; set; }
        public string Cod_Domeniu { get; set; }
        public Nullable<decimal> CA_Ultimul_An { get; set; }
        public Nullable<int> Nr_Angajati { get; set; }
        public string Sursa_Info_Prospect { get; set; }
        public string Sursa_Info_Prospect_Alt { get; set; }
        public string Id_User { get; set; }
        public System.DateTime Data_Intro { get; set; }
        public System.DateTime Data_Modif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prospecte_ContactPlus> Prospecte_ContactPlus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prospecte_Pasi_Urmatori> Prospecte_Pasi_Urmatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prospecte_ProfilPlus> Prospecte_ProfilPlus { get; set; }
    }
}
