//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecte_Pasi_Urmatori
    {
        public int Id { get; set; }
        public int Id_Prospect { get; set; }
        public string Nume_Pas { get; set; }
        public Nullable<int> Cod_Nume_Pas { get; set; }
        public System.DateTime Data_Scadenta_Pas { get; set; }
        public string Stare_Pas { get; set; }
        public Nullable<int> Cod_Stare_Pas { get; set; }
        public Nullable<int> Index_Efectuare_Pas { get; set; }
        public Nullable<int> Index_Neefectuare_Pas { get; set; }
        public Nullable<int> Index_Reprogramare_Pas { get; set; }
        public Nullable<bool> Pas_Activ { get; set; }
        public Nullable<byte> Ora_Pas { get; set; }
        public Nullable<byte> Durata_Pas { get; set; }
        public Nullable<decimal> Grad_Realizare_Pas { get; set; }
        public Nullable<byte> Prioritate_Pas { get; set; }
        public string Raspuns_Pas { get; set; }
        public string Referinta_Raspuns_Pas { get; set; }
        public Nullable<int> Cod_Raspuns_Pas { get; set; }
        public string Detalii_Raspuns_Pas { get; set; }
        public Nullable<decimal> Nivel_Financiar_Subiect { get; set; }
        public Nullable<int> Timp_Afectat_Subiect_Pas { get; set; }
        public string Obstacol_Pas { get; set; }
        public Nullable<int> Cod_Obstacol_Pas { get; set; }
        public string Comentariu_Obstacol_Pas { get; set; }
        public string Comentariu_Automat_Pas { get; set; }
        public string Info_Tipuri_Produse_Cautate { get; set; }
        public string Info_Detalii_Produse_Cautate { get; set; }
        public string Info_Furnizori { get; set; }
        public string Info_Furnizor_Principal { get; set; }
        public string Info_Detalii_Furnizori { get; set; }
        public string Info_Tip_Motivatii { get; set; }
        public string Info_Detalii_Motivatii { get; set; }
        public string Info_Alte_Info { get; set; }
        public string Conexe_Subiect { get; set; }
        public string Referinta_Conexe_Subiect { get; set; }
        public Nullable<int> Cod_Conexe_Subiect { get; set; }
        public string Detalii_Conexe_Subiect { get; set; }
        public string Id_User { get; set; }
        public System.DateTime Data_Intro { get; set; }
        public System.DateTime Data_Modif { get; set; }
    
        public virtual Prospecte_Profil Prospecte_Profil { get; set; }
    }
}
