//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashboardProspect
    {
        public Nullable<long> Id_Vw { get; set; }
        public int Id_Prospect { get; set; }
        public string Tip_Prospect_PF_PJ { get; set; }
        public string Nume_Prospect { get; set; }
        public string Cod_Prospect { get; set; }
        public string Tara { get; set; }
        public string Domeniu { get; set; }
        public string Cod_Domeniu { get; set; }
        public Nullable<decimal> CA_Ultimul_An { get; set; }
        public Nullable<int> Nr_Angajati { get; set; }
        public string Sursa_Info_Prospect { get; set; }
        public string Sursa_Info_Prospect_Alt { get; set; }
        public string Id_User_Profil { get; set; }
        public System.DateTime Data_Intro_Profil { get; set; }
        public System.DateTime Data_Modif_Profil { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> Id_Prospect_Contact { get; set; }
        public string Persoana_Decizie { get; set; }
        public string Telefon { get; set; }
        public string Regiune_Reper { get; set; }
        public string Adresa_Text { get; set; }
        public string Cod_Postal { get; set; }
        public string Email { get; set; }
        public string Web_Site { get; set; }
        public string Adresa_Numar { get; set; }
        public string Adresa_Strada { get; set; }
        public string Adresa_Oras { get; set; }
        public string Adresa_Unitate_Regionala { get; set; }
        public string Adresa_SubUnitate_Regionala { get; set; }
        public string Persoana_Decizie_Nume { get; set; }
        public string Persoana_Decizie_Prenume { get; set; }
        public string Persoana_Decizie_Nume_Alt { get; set; }
        public string Persoana_Decizie_Prenume_Alt { get; set; }
        public string Persoana_Decizie_Sex { get; set; }
        public string Persoana_Decizie_Functie { get; set; }
        public string Telefon_Alt { get; set; }
        public string Email_Alt { get; set; }
        public string Id_User_Contact { get; set; }
        public Nullable<System.DateTime> Data_Intro_Contact { get; set; }
        public Nullable<System.DateTime> Data_Modif_Contact { get; set; }
        public Nullable<int> Id_ContactPlus { get; set; }
        public Nullable<int> Id_Prospect_ContactPlus { get; set; }
        public string Telefon_Secretariat_1 { get; set; }
        public string Telefon_Secretariat_2 { get; set; }
        public string Telefon_Secretariat_3 { get; set; }
        public string Email_Office { get; set; }
        public string Persoana_Decizie_PD2 { get; set; }
        public string Telefon_PD2 { get; set; }
        public string Email_PD2 { get; set; }
        public string Persoana_Decizie_Nume_PD2 { get; set; }
        public string Persoana_Decizie_Prenume_PD2 { get; set; }
        public string Persoana_Decizie_Nume_Alt_PD2 { get; set; }
        public string Persoana_Decizie_Prenume_Alt_PD2 { get; set; }
        public string Persoana_Decizie_Sex_PD2 { get; set; }
        public string Persoana_Decizie_Functie_PD2 { get; set; }
        public string Telefon_Alt_PD2 { get; set; }
        public string Email_Alt_PD2 { get; set; }
        public string Persoana_Decizie_PD3 { get; set; }
        public string Telefon_PD3 { get; set; }
        public string Email_PD3 { get; set; }
        public string Persoana_Decizie_Nume_PD3 { get; set; }
        public string Persoana_Decizie_Prenume_PD3 { get; set; }
        public string Persoana_Decizie_Nume_Alt_PD3 { get; set; }
        public string Persoana_Decizie_Prenume_Alt_PD3 { get; set; }
        public string Persoana_Decizie_Sex_PD3 { get; set; }
        public string Persoana_Decizie_Functie_PD3 { get; set; }
        public string Telefon_Alt_PD3 { get; set; }
        public string Email_Alt_PD3 { get; set; }
        public string Comentariu_Date_Contact_1 { get; set; }
        public string Comentariu_Date_Contact_2 { get; set; }
        public string Comentariu_Date_Contact_3 { get; set; }
        public string Id_User_ContactPlus { get; set; }
        public Nullable<System.DateTime> Data_Intro_ContactPlus { get; set; }
        public Nullable<System.DateTime> Data_Modif_ContactPlus { get; set; }
        public Nullable<int> Id_ProfilPlus { get; set; }
        public Nullable<int> Id_Prospect_ProfilPlus { get; set; }
        public Nullable<bool> Aprobare_GDPR { get; set; }
        public string Detalii_GDPR { get; set; }
        public string Referinta_GDPR { get; set; }
        public Nullable<bool> Posibilitate_Montaj { get; set; }
        public string Detalii_Tip_Montaj { get; set; }
        public string Referinta_Montaj { get; set; }
        public Nullable<bool> Prospect_Activ { get; set; }
        public string Status_Prospect { get; set; }
        public Nullable<int> Cod_Status_Prospect { get; set; }
        public string Comentariu_Prospect { get; set; }
        public Nullable<bool> Z_Bit_Field { get; set; }
        public Nullable<int> Z_Int_Field { get; set; }
        public string Z_String_Field { get; set; }
        public string Z_Text_Field { get; set; }
        public string User_Alocat { get; set; }
        public Nullable<System.DateTime> Data_Alocare { get; set; }
        public string Id_User_ProfilPlus { get; set; }
        public Nullable<System.DateTime> Data_Intro_ProfilPlus { get; set; }
        public Nullable<System.DateTime> Data_Modif_ProfilPlus { get; set; }
        public Nullable<int> Id_Pasi { get; set; }
        public Nullable<int> Id_Prospect_Pasi { get; set; }
        public string Nume_Pas { get; set; }
        public Nullable<int> Cod_Nume_Pas { get; set; }
        public Nullable<System.DateTime> Data_Scadenta_Pas { get; set; }
        public string Stare_Pas { get; set; }
        public Nullable<int> Cod_Stare_Pas { get; set; }
        public Nullable<int> Index_Efectuare_Pas { get; set; }
        public Nullable<int> Index_Neefectuare_Pas { get; set; }
        public Nullable<int> Index_Reprogramare_Pas { get; set; }
        public Nullable<bool> Pas_Activ { get; set; }
        public Nullable<byte> Ora_Pas { get; set; }
        public Nullable<byte> Durata_Pas { get; set; }
        public Nullable<decimal> Grad_Realizare_Pas { get; set; }
        public Nullable<byte> Prioritate_Pas { get; set; }
        public string Raspuns_Pas { get; set; }
        public string Referinta_Raspuns_Pas { get; set; }
        public Nullable<int> Cod_Raspuns_Pas { get; set; }
        public string Detalii_Raspuns_Pas { get; set; }
        public Nullable<decimal> Nivel_Financiar_Subiect { get; set; }
        public Nullable<int> Timp_Afectat_Subiect_Pas { get; set; }
        public string Obstacol_Pas { get; set; }
        public Nullable<int> Cod_Obstacol_Pas { get; set; }
        public string Comentariu_Obstacol_Pas { get; set; }
        public string Comentariu_Automat_Pas { get; set; }
        public string Info_Tipuri_Produse_Cautate { get; set; }
        public string Info_Detalii_Produse_Cautate { get; set; }
        public string Info_Furnizori { get; set; }
        public string Info_Furnizor_Principal { get; set; }
        public string Info_Detalii_Furnizori { get; set; }
        public string Info_Tip_Motivatii { get; set; }
        public string Info_Detalii_Motivatii { get; set; }
        public string Info_Alte_Info { get; set; }
        public string Conexe_Subiect { get; set; }
        public string Referinta_Conexe_Subiect { get; set; }
        public Nullable<int> Cod_Conexe_Subiect { get; set; }
        public string Detalii_Conexe_Subiect { get; set; }
        public string Id_User_Pasi { get; set; }
        public Nullable<System.DateTime> Data_Intro_Pasi { get; set; }
        public Nullable<System.DateTime> Data_Modif_Pasi { get; set; }
    }
}
