//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMnAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashboardClient
    {
        public long ID_Vw { get; set; }
        public int ID_PRE_Client_Profil { get; set; }
        public string Tip_Client_PF_PJ_Profil { get; set; }
        public string Nume_Client { get; set; }
        public string Cod_Client { get; set; }
        public string Tara { get; set; }
        public string Domeniu { get; set; }
        public string Cod_Domeniu { get; set; }
        public Nullable<decimal> CA_Ultimul_An { get; set; }
        public Nullable<int> Nr_Angajati { get; set; }
        public string Sursa_Info_Client { get; set; }
        public string ID_USER { get; set; }
        public Nullable<System.DateTime> Data_Intro { get; set; }
        public string Sursa_Info_Client_Alt { get; set; }
        public Nullable<System.DateTime> Data_Modif { get; set; }
        public Nullable<int> ID_Contact { get; set; }
        public Nullable<int> ID_PRE_Client_Contact { get; set; }
        public string Persoana_Decizie { get; set; }
        public string Telefon { get; set; }
        public string Regiune_Reper { get; set; }
        public string Adresa_Text { get; set; }
        public string Cod_Postal { get; set; }
        public string Email { get; set; }
        public string Web_Site { get; set; }
        public string Adresa_Numar { get; set; }
        public string Adresa_Strada { get; set; }
        public string Adresa_Oras { get; set; }
        public string Adresa_Unitate_Regionala { get; set; }
        public string Adresa_SubUnitate_Regionala { get; set; }
        public string Persoana_Decizie_Nume { get; set; }
        public string Persoana_Decizie_Prenume { get; set; }
        public string Persoana_Decizie_Nume_Alt { get; set; }
        public string Persoana_Decizie_Prenume_Alt { get; set; }
        public string Persoana_Decizie_Sex { get; set; }
        public string Persoana_Decizie_Functie { get; set; }
        public string Telefon_Alt { get; set; }
        public string Email_Alt { get; set; }
        public string ID_USER_Contact { get; set; }
        public Nullable<System.DateTime> Data_Intro_Contact { get; set; }
        public Nullable<System.DateTime> Data_Modif_Contact { get; set; }
        public Nullable<int> ID_Interlocutor { get; set; }
        public Nullable<int> ID_PRE_Client_Interlocutor { get; set; }
        public string Obs_Tipuri_Produse_Cautate { get; set; }
        public Nullable<System.DateTime> Data_Discutie { get; set; }
        public string Obs_Furnizori_Actuali_Client { get; set; }
        public string Obs_Dureri_Client { get; set; }
        public string Obs_Alte_Observatii { get; set; }
        public Nullable<int> Durata_Discutie_Minute { get; set; }
        public Nullable<int> ID_Discutie { get; set; }
        public string Tip_Discutie { get; set; }
        public string Tip_STADIU_DISCUTIE { get; set; }
        public string ID_USER_Interlocutor { get; set; }
        public Nullable<System.DateTime> Data_Intro_Interlocutor { get; set; }
        public Nullable<System.DateTime> Data_Modif_Interlocutor { get; set; }
    }
}
